site_name: DOCUMENTAÇÃO - LICITA BSB
repo_url: https://github.com/unb-mds/2024-1-Squad-03

nav: 
  - Home: index.md
  - Como executar o projeto: execution.md
  - Sprints:
    - Sprint 0:
      - Reunião 1: Atas/Sprint0_reunião1.md
      - Reunião 2: Atas/Sprint0_reunião2.md
    - Sprint 1:
      - Reunião 1: Atas/Sprint1_reunião1.md
      - Reunião 2: Atas/Sprint1_reunião2.md
    - Sprint 2:
      - Reunião 1: Atas/Sprint2_reunião1.md
      
  - Materiais de Estudos: Estudos/Estudos.md
  - Organização da Equipe: OrganizacaoEquipe/Cargos do Time.md

theme: 
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.copy
  icon:
    repo: fontawesome/brands/github

