name: Script de automação da extração das Licitações de Brasília

on:
  schedule:
    - cron: '18 19 * * *'

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install beautifulsoup4
        pip install urllib3
    - name: Python Script
      run: python backend/data_collection_DOU_diario/main.py

    - name: Commit and push updated last date
      run: |
        git config user.name "Github Actions"
        git config user.email "actions@users.noreply.github.com"
        git pull origin main
        git add --all
        git commit -m "As licitações de brasília foram extraídas com sucesso!"
        git push
