name: Script de automação da extração das Licitações de Brasília

on:
  schedule:
    - cron: '25 19 * * *'  # Executa todos os dias às 19:18 UTC

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Garante que você tenha todo o histórico do Git

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install beautifulsoup4
        pip install urllib3

    - name: Run Python script
      run: python backend/data_collection_DOU_diario/main.py

    - name: Commit and push updated last date
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "Github Actions"
        git config --global user.email "actions@users.noreply.github.com"
        git pull origin main
        git add --all
        git commit -m "As licitações de Brasília foram extraídas com sucesso!"
        git push
